### ISSUE TITLE
plot_multilevel doesn't plot more than two levels

### ISSUE THREAD

**Issue by jhollway** [stocnet/manynet#14]
**[Original report](https://bitbucket.org/jhollway/roctopus/issue/16) by James Hollway (Bitbucket: [jhollway](https://bitbucket.org/jhollway), GitHub: [jhollway](https://github.com/jhollway)).**

----------------------------------------

**Comment by henriquesposito** [comment]
`autographr(ison_lotr, layout = "multilevel", node_color = "Race", level = "Race")`
