### ISSUE TITLE
Compatibility with igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [stocnet/manynet#34]
@snlab-ch @henriquesposito @jaeltan @jhollway: This package fails its checks for the release candidate for igraph 2.0.0. See <https://github.com/igraph/rigraph/blob/igraph-0.10/revdep/problems.md> for details.

Is this a problem in your package? Should we be doing things differently?

Install the 2.0.0 release candidate using `pak::pak("igraph/rigraph@igraph-0.10")` .

We're planning to release igraph 2.0.0 just before CRAN's closing on Christmas. This should give us at least until mid-January to resolve this and keep CRAN happy at the same time. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/989.

**Comment by krlmlr** [comment]
New anticipated release data: January 12.

**Comment by jhollway** [comment]
We have updated function names, but cannot replicate other issues until it is on CRAN.

**Comment by krlmlr** [comment]
Thanks, interesting. Why do you need igraph to be on CRAN to replicate the other issues?

**Comment by jhollway** [comment]
We're looking into it.

**Comment by henriquesposito** [comment]
Thank you for opening the issue and for the reminder @krlmlr. Our team had several issues downloading and installing the newest versions of igraph this past month. I was able to compile/install/load the latest version of igraph today and confirm that we can now reproduce the issue. We will do our best to adress this and other issues promptly. Thank you once again.

**Comment by jhollway** [comment]
@krlmlr, we believe we have fixed the relevant issues on the develop branch but also need to tidy up some other changes. Please go ahead and submit igraph 2.0.0; we should be ready to merge and submit to CRAN shortly.
