### ISSUE TITLE
Make `graphr/s/t` functions accept arguments following US and British spelling  

### ISSUE THREAD

**Issue by henriquesposito** [stocnet/manynet#41]
`graphr(ison_adolescents, node_color = "blue")` should be equivalent to `graphr(ison_adolescents, node_colour = "blue")`

**Comment by jhollway** [comment]
Could the `...` be used to handle this? That is, if a user writes `node_colour = "green"`, then we can list and look in the dot parameter `...` for known aliases such as `colour`, check that this is not a repetition (e.g. `node_color = "blue", node_colour = "green"`), and if not apply the value/vector instead to `node_color` internally and at the outset?

**Comment by jhollway** [comment]
Should we maybe put those extra arguments later in the argument order so that one could, hypothetically, explicate them in order? E.g.:

```
graphr(ison_adolescents, "stress", TRUE, "green", "square", 12) # etc
```
